export type Analyse = {
    PercentOfSpeechTypeAccordance: number,
    PercentOfWordsParasites: number,
    WordsParasites: number,
    PercentOfWordsRepetitions: number,
    WordsRepetitions: number,
    PercentOfSpeechPlaceAccordance: number,
    SpeedSpechAccordance: number,
    AudibilityAccordance: number,
    PercentOfFacialExpressionAccordance: number,
    PercentOfGesturesAccordance: number,
    PercentOfArticulationAccordance: number,
    PercentOfFormAccordance: number,
    Tips: null | any,
    Articles: null | any,
};
